# Generated by Django 3.2.3 on 2021-06-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='default country', max_length=200),
            preserve_default=False,
        ),
    ]
